services:
  api1: &api
    image: ${DOCKER_REGISTRY-}paymentprocessorapi
    build:
      context: .
      dockerfile: PaymentProcessor.Api/Dockerfile
    hostname: api1
    networks:
      - backend
      - payment-processor
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "250MB"

  nginx:
    image: nginx:1.29.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - backend
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "yes"]
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "150MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true